name: Concurrency Deploy

concurrency:
  group: deploy-${{ github.event.inputs.stage }}
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      stage:
        description: 'Environment'
        required: true
        type: string
        
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          wait(1000)
          echo "deploy ${{ github.event.inputs.stage }}"
