name: Concurrency Deploy

concurrency: deploy

on:
  workflow_call:
    inputs:
      stage:
        description: 'Environment'
        required: true
        type: string
        
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 30s
          echo "deploy ${{ github.event.inputs.stage }}"
