name: Concurrency Deploy

concurrency: 
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      stage:
        description: 'Environment'
        required: true
        type: string
      sleep:
        description: 'time to sleep'
        required: true
        type: string
        default: 30s
        
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep ${{ github.event.inputs.sleep }}
          echo "deploy ${{ github.event.inputs.stage }}"
