name: Concurrency Deploy

concurrency: 
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      stage:
        description: 'Environment'
        required: true
        type: string
      sleepDuration:
        description: 'time to sleep'
        required: false
        type: string
        default: '30s'
        
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.sleepDuration }}"
          sleep ${{ inputs.sleepDuration }}
          echo "deploy ${{ github.event.inputs.stage }}"
