name: Concurrency Deploy

# concurrency: deploy-${{ github.event.inputs.stage }}

# definition of a concurrency group at this position did not work
# only the github context can be used
# but we need inputs.stage instead of github.event.inputs.stage

on:
  workflow_call:
    inputs:
      stage:
        description: 'Environment'
        required: true
        type: string
      sleepDuration:
        description: 'time to sleep'
        required: false
        type: string
        default: '30s'
        
jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.stage }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.sleepDuration }}"
          sleep ${{ inputs.sleepDuration }}
          echo "deploy ${{ github.event.inputs.stage }}"
