name: Concurrency Starter

on:
  workflow_dispatch
  
jobs: 
  deploy-develop:
    name: Deploy develop
    concurrency: deploy-develop
    uses: ./.github/workflows/concurrencyDeploy.yml
    with:
      stage: develop
      sleepDuration: '1m'
      
  deploy-fit:
    name: Deploy fit
    concurrency: deploy-fit
    uses: ./.github/workflows/concurrencyDeploy.yml
    with:
      stage: fit
      sleepDuration: '10s'
      
  deploy-live:
    name: Deploy live
    concurrency: deploy-live
    needs: [ deploy-fit ]
    uses: ./.github/workflows/concurrencyDeploy.yml
    with:
      stage: live
