name: Concurrency Starter

on:
  workflow_dispatch
  
jobs: 
  deploy-develop:
    name: Deploy develop
    uses: ./.github/workflows/concurrencyDeploy.yml
    concurrency: deploy
    with:
      stage: develop
      sleep: 1m
      
  deploy-fit:
    name: Deploy fit
    uses: ./.github/workflows/concurrencyDeploy.yml
    concurrency: deploy
    with:
      stage: fit
      sleep: 10s
      
  deploy-live:
    name: Deploy live
    needs: [ deploy-fit ]
    uses: ./.github/workflows/concurrencyDeploy.yml
    concurrency: deploy
    with:
      stage: live
