name: GitHub CLI Examples

on:
  workflow_dispatch
  
jobs: 
  create-label:
    name: Create label on the fly
    runs-on: ubuntu-latest
    steps:
      - name: Create major label
        run: gh label create major --description "Major update for a dependency file" --color 006B75
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
