name: Gradle (node plugin + setup-gradle + setup-node)

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  gradleBuildWithSetupGradleAndNode:
    strategy:
      matrix:
        version: [ 1, 2, 3, 4, 5 ]
    name: "With setup-gradle-node run ${{ matrix.version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: |
          ./gradlew npm_version
          ./gradlew npmEsLint
          ./gradlew npmTest 
