name: Gradle (node plugin)

on:
  workflow_dispatch:
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### :clipboard: Input parameters of this workflow run: " >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  gradleBuild:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 

  gradleBuildWithSetupGradle:
    name: Gradle build with setup-gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 

  gradleBuildWithSetupGradle2:
    name: Gradle build with setup-gradle (2)
    needs: gradleBuildWithSetupGradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 

  gradleBuildWithSetupNode:
    name: Gradle build with setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 
