name: Gradle (node plugin)

on:
  workflow_dispatch:
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### :clipboard: Input parameters of this workflow run: " >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  gradleBuild:
    strategy:
      matrix:
        version: [ 1, 2, 3, 4, 5 ]
    name: "Gradle node ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 
