name: Gradle (node plugin + setup-gradle)

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  gradleBuildWithSetupGradle:
    strategy:
      matrix:
        version: [ 1, 2, 3, 4, 5 ]
    name: "With setup-gradle run ${{ matrix.version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - run: |
          ./gradlew npm_version
          ./gradlew npmEsLint
          ./gradlew npmTest 

