name: Gradle (node plugin)

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  gradleBuild:
    strategy:
      matrix:
        version: [ 1, 2, 3, 4, 5 ]
    name: "Gradle node run ${{ matrix.version }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./gradlew npmEsLint
          ./gradlew npmTest 
