name: Starter Gradle (node plugin)

on:
  workflow_dispatch:
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### :clipboard: Input parameters of this workflow run: " >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-gradle-node:
    name: Gradle node
    uses: ./.github/workflows/gradleNode.yml

  workflow-gradle-node-setup-gradle:
    name: With setup gradle
    uses: ./.github/workflows/gradleNodeWithSetupGradle.yml

  workflow-gradle-node-setup-node:
    name: With setup node
    uses: ./.github/workflows/gradleNodeWithSetupNode.yml

  workflow-gradle-node-setup-gradle-and-node:
    name: With setup gradle and node
    uses: ./.github/workflows/gradleNodeWithSetupGradleAndNode.yml


