name: Using of a matrix

on:
  workflow_dispatch
  
jobs:
  example-matrix:
    strategy:
      matrix:
        title: [ first, second ]
        value: [ 1, 2, 3 ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.title }}: ${{ matrix.value }}"
              
          
