name: Using of a matrix

on:
  workflow_dispatch
  
jobs:
  example-matrix:
    strategy:
      matrix:
        title: [ first, second ]
        value: [ 1, 2, 3 ]
    name: "Run ${{ matrix.title }} : ${{ matrix.value }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.title }} = ${{ matrix.value }}"
      
  example-alarm:
    strategy:
      matrix:
        alarmName: [ "MinInstances", "Errors" ]
        stage: [ live, develop ]
        include:
          - alarmName: "Http5XX"
            stage: live
          - alarmName: "MinRequestCount"
            stage: live
    name: "Run ${{ matrix.alarmName }} : ${{ matrix.stage }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.alarmName }} = ${{ matrix.stage }}"
      
  matrix-with-includes:
    strategy:
      matrix:
        title: [ first, second ]
        value: [ 1, 2, 3 ]
        include:
          - anotherValue: test
          - title: first
            anotherValue: test-first
    name: "Run with includes: ${{ matrix.title }} : ${{ matrix.value }}, ${{ matrix.anotherValue }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.title }} = ${{ matrix.value }} + ${{ matrix.anotherValue }}"
