name: Using of a matrix

permissions:
  id-token: write

on:
  workflow_dispatch
  
jobs:
  example1:
    strategy:
      matrix:
        title: [ first, second ]
        value: [ 1, 2, 3 ]
    name: simple matrix
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "${{ matrix.title }: ${{ matrix.value }}"
              
          
