name: Skipping a job with a reusable workflow

on:
  workflow_call:
    inputs:
      skipJob: 
        type: string # boolean is not working https://github.com/actions/runner/issues/1483
        default: true
        required: false
  
jobs:
  example-job-1:
    name: "Run job"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run job: skip = ${{ github.event.inputs.skipJob }}"
          
  example-job-2:
    name: "Skip job"
    if: ${{ github.event.inputs.skipJob == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "should not run"
      
  example-job-3:
    name: "Skip another job"
    if: ${{ github.event.inputs.skipJob != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "should not run"
