name: Starter

on:
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
  
jobs:
  info:
    name: Input values
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "### Inputs :clipboard: \
          ~~~ \
          skipJob = ${{ github.event.inputs.skipJob }} \
          ~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-afterdeploy-test:
    name: Tests
    if: ${{ !github.event.inputs.skipJob }}
    uses: ./.github/workflows/reusableSkip.yml
    
  workflow-fit:
    name: Fit
    if: success() || github.event.inputs.skipJob
    needs: [ workflow-afterdeploy-test ]
    uses: ./.github/workflows/reusableWorkflow.yml
