name: Starter

on:
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### Workflow run with inputs :clipboard:" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "skipJob = ${{ github.event.inputs.skipJob }}" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-test:
    name: Tests
    if: ${{ github.event.inputs.skipJob == 'false' }}
    uses: ./.github/workflows/reusableRun.yml
    
  workflow-fit:
    name: Fit
    if: ${{ github.action_status == 'success' }}
    needs: [ workflow-test ]
    uses: ./.github/workflows/reusableRun.yml
    
  summary:
    name: summary
    runs-on: ubuntu-latest
    needs: [ workflow-test ]
    if: always()
    steps:
      - run: |
          echo "status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "status test: ${{ needs.workflow-test.status }}" >> $GITHUB_STEP_SUMMARY
