name: Starter

on:
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### :clipboard: Input parameters of this workflow run: " >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "skipJob = ${{ github.event.inputs.skipJob }}" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-to-be-skipped:
    name: "Tests: :repeat:"
    uses: ./.github/workflows/withSkippedJobs.yml
    
  workflow-should-run-after-skipped-workflow:
    name: Fit
    needs: [ workflow-to-be-skipped ]
    uses: ./.github/workflows/reusableRun.yml
    
  workflow-to-be-skipped-not-working:
    name: Tests2
    if: github.event.inputs.skipJob == 'false'
    uses: ./.github/workflows/withFailingJob.yml
    
  workflow-should-run-after-skipped-workflow-not-working:
    name: Fit2
    if: success() || github.event.inputs.skipJob == 'true'
    needs: [ workflow-to-be-skipped-not-working ]
    uses: ./.github/workflows/reusableRun.yml
