name: Starter

on:
  workflow_dispatch
  
jobs:
  workflow-afterdeploy-test:
    name: Tests
    uses: ./.github/workflows/reusableWorkflow.yml
    
  workflow-fit:
    name: Fit
    needs: [ workflow-afterdeploy-test ]
    uses: ./.github/workflows/reusableWorkflow.yml
