name: Starter

on:
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### Workflow run with inputs :clipboard:" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "skipJob = ${{ github.event.inputs.skipJob }}" >> $GITHUB_STEP_SUMMARY
          echo "no more params" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-to-be-skipped:
    name: Tests
    uses: ./.github/workflows/withSkippedJobs.yml
    
  workflow-should-run-after-skipped-workflow:
    name: Fit
    needs: [ workflow-to-be-skipped ]
    uses: ./.github/workflows/reusableRun.yml
