name: Starter

on:
  workflow_dispatch:
    inputs:
      skipJob: 
        type: boolean
        default: true
        required: false
  
jobs:
  info:
    name: Print input values
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### Inputs :clipboard:" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          echo "skipJob = ${{ github.event.inputs.skipJob }}" >> $GITHUB_STEP_SUMMARY
          echo "skipJob = ${{ github.event.inputs.skipJob }}" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          
  workflow-test:
    name: Tests
    if: ${{ !github.event.inputs.skipJob }}
    uses: ./.github/workflows/reusableSkip.yml
    
  workflow-fit:
    name: Fit
    if: success() || github.event.inputs.skipJob
    needs: [ workflow-test ]
    uses: ./.github/workflows/reusableWorkflow.yml
