name: Test reporter

on:
  workflow_dispatch:
  
jobs:
  dorny:
    name: Test dorny test reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Copy test data
        run: |
          ./gradlew --no-daemon testClasses

      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ./**/build/test-results/test/TEST-*.xml
          reporter: java-junit