name: Test reporter

on:
  workflow_dispatch:
  
jobs:
  dorny:
    name: Test dorny test reporter
    runs-on: ubuntu-latest
    steps:
      - name: Copy test data
        run: |
          ./gradlew --no-daemon testClasses

      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ./**/build/resources/main/test/TEST-*.xml
          reporter: java-junit