name: Test reporter

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write
  pull-requests: write

jobs:
  dorny:
    name: Test dorny test reporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Create test data
        run: |
          ./gradlew --no-daemon test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports-test
          path: build/reports/

      - name: Generate test report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ./**/build/test-results/test/TEST-*.xml
          reporter: java-junit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results/**/*.xml"