name: Watcher

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/events/*'
  
jobs: 
  do-it:
    name: do it
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "### :clipboard: Triggered by ${{ github.event }}" >> $GITHUB_STEP_SUMMARY
    
