name: Watcher

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/events/*'
  
jobs: 
  do-it:
    name: do it
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
    
